### ISSUE TITLE
Spdy fallback

### ISSUE THREAD

**Issue by coolfeature** [extend/bullet#71]
Would be nice if bullet attempted spdy first before falling back onto ws and http. If not possible please advise what would have to be changed in Cowboy first.

**Comment by essen** [comment]
Not sure what you mean. SPDY is like HTTP.

**Comment by coolfeature** [comment]
Yeah, sorry, please ignore, I will re-open for cowboy, I am trying to find out what is the best way of setting cowboy up to do spdy and http depending on what the client supports...

**Comment by essen** [comment]
start_spdy instead of start_https. Not much to say there. It's all explained in the docs.
